### ISSUE TITLE
Minor: "Mark as completed" button appears on future chores (which cannot be marked as completed)

### ISSUE THREAD

**Issue by zmbc** [HomeDivision/Choreless#20]
Steps:
- Go to the "Weekly Schedule" page
- Click "Select a chore to add" and click one of the options (it doesn't matter)
- *While that chore is on the side of the schedule*, click it and mark it as completed
- Move the chore onto a day, which also assigns it to yourself
- **Slightly surprising:** chore returns to the "completed: false" state
- **Very surprising**: chore cannot be marked as completed (the button does not change that the chore says "completed: false"

**Comment by jimmybnguyen** [comment]
Was the chore card moved to a day not sunday? Per our requirement specs, a chore card cannot be marked as complete if it is set to a future day of the week (altho we did a poor job in showing this). Also, chore returns to completed false once moved is a feature since you are reassigning a chore to a different day

**Comment by zmbc** [comment]
@jimmybnguyen Ahh, that explains it. I guess the issue here, then, is that the "mark as complete" button still appears and is clickable for future chores. It definitely looked like it was supposed to do something.

**Comment by imdodrill** [comment]
Removed the complete option for chores that are on a future day
