### ISSUE TITLE
[Major] Cannot 'Mark as Complete' if the chore is in the future

### ISSUE THREAD

**Issue by johnyunjr** [HomeDivision/Choreless#32]
This may be an intended purpose, but it might be better to include a description that chores can only be 'Marked as Complete' on the day of the chore or if the day has passed.

Chores may be finished a day early. It might be nice to include a group option to choose whether future chores are able to be 'Marked as Complete.' Currently, you cannot drag a completed card into a day later in the week or else it will automatically change the value to 'false.' So no workaround is available.

![mark](https://cloud.githubusercontent.com/assets/14932301/26803402/ea8549fc-49f8-11e7-849b-9ce81866b8a3.PNG)

**Comment by jimmybnguyen** [comment]
Per our requirements spec, a chore cannot be mark as completed if it's assigned for a future day (altho we did a poor job in showing this). As for completing a chore early, our idea was that users will drag that chore card over to the day they completed it, then mark it as complete. We never intended for a completed chore cards to be set later in a future day of the week because if a chore was completed earlier, it should be moved over to that day.

**Comment by imdodrill** [comment]
removed 'mark as complete' option from future chores and added an indication of the current day of the week.
